### ISSUE TITLE
broken?

### ISSUE THREAD

**Issue by thonium** [dado3212/PollDaddyHack#2]
hi is it possible this script is broken?

Traceback (most recent call last):
  File "vote.py", line 34, in <module>
    vote_once(poll_id, answer_id)
  File "vote.py", line 14, in vote_once
    send = c.get(request, headers=redirect, verify=False)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ResponseNotReady())

could you have a look? thanks!

**Comment by dado3212** [comment]
Make sure you have the most up to date version of 'requests'.
