### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by PTSTUDIOS** [dado3212/PollDaddyHack#20]
Can anybody confirm whether this script still works?  I am getting the following error.

```
Traceback (most recent call last):
  File "C:\polldaddy\vote.py", line 103, in <module>
    vote(poll_id, answer_id, number_of_votes, wait_min, wait_max)
  File "C:\polldaddy\vote.py", line 77, in vote
    b = vote_once(form, value)
  File "C:\polldaddy\vote.py", line 57, in vote_once
    data = re.search("data-vote=\"(.*?)\"",init.text).group(1).replace('&quot;','"')
AttributeError: 'NoneType' object has no attribute 'group'
```

I wonder if Polldaddy has changed its code, making some of this script obsolete.

**Comment by dado3212** [comment]
Can't repro this, I think it's still working.  As is, this repo isn't being updated anymore, but you're welcome to submit a PR for your case.
