### ISSUE TITLE
new errors 

### ISSUE THREAD

**Issue by leonku** [dado3212/PollDaddyHack#6]
hello great script though i am having issues with the following error. 

using latest version of python 

Traceback (most recent call last):
  File "C:\Users\student\Desktop\PollDaddyHack-master\vote.py", line 43, in <module>
    vote(poll_id, answer_id, number_of_votes)
  File "C:\Users\student\Desktop\PollDaddyHack-master\vote.py", line 31, in vote
    print (time  + str(i) +
TypeError: unsupported operand type(s) for +: 'module' and 'str'

**Comment by dado3212** [comment]
That's never been a version.  Line 31 is: `print "Voted (time number " + str(i) + ")!"`. Make sure that you wrap `time` in quotes, or it will treat it like the time module.
